sealdice/sealdice-core

- dice/ext_fun.go
- go.mod
圣殿团的身份抽取似乎需要暗中发放，所以增加了一个 `.drlh` 指令，基本就是 `.drl` 的暗骰版。
另外，修改了 `.drl` 和 `.jsr` 的帮助文本，力图更易懂。
> `drl` 现在支持暗骰抽取

- dice/ext_fun.go
`drl` 和 `jsr` 的骰点上限现在是 25 次，和 cmd_parse.go 中规定的一致。
> 限制了 `jsr` 和 `drl` 的骰点上限

- .github/workflows/ci.yml
- dice/dice.go
- dice/gocqhttp_helper.go
- dice/platform_adapter_discord.go
- dice/platform_adapter_kook.go
- main.go
- utils/procs/procs.go
chore: 在Android平台下拉起gocq时主动设置其环境变量
chore: 为ExtInfo.AutoActive添加jsbind
> chore: 移除kook/discord平台的代码块包裹

- api/conn.go
- dice/discord_helper.go
- dice/platform_adapter_discord.go
- feat:添加Discord 账号的 http 代理配置
- fix:Discord toStdMessage 时调用了错误的函数导致无法发送消息
> feat:添加Discord 账号的 http 代理配置

- dice/dice.go
- dice/im_session.go
- dice/platform_adapter_discord.go
- dice/platform_adapter_kook.go
- go.mod
修复了一个 #140 中导致 `(*MsgContext).Notice` 无法正确发送消息通知的问题
加入新服务器时，触发 JS 插件的 `onGuildJoined` 事件，主要在 `msg` 中包含 `guildId`。
同时采取方法发送入群致辞。
> fix: PR#140 导致无法发送通知的问题；添加 `OnGuildJoined` 事件并适配 KOOK 与 Discord

- dice/dice_help.go
- go.mod
- 修复帮助目录下存在多级时不读取的问题
- 读取帮助文件时，过滤以.开头的文件 （主要处理mac端的.DS_Store）
> fix(helpdoc): 帮助文档相关问题修复

- dice/ext_coc7.go
若玩家投出了高于当前技能值的结果，或者结果大于95，则调查员该技能获得改善：骰1D10并且立即将结果加到当前技能值上。技能可通过此方式超过100%。
> fix: en 指令掷骰结果超过 95 时也应该成长

- dice/im_helpers.go
- dice/im_session.go
一个问题：跨平台时构建的 ctx 和 msg 会被一系列方法读取，包括插件的 OnMessageSend 事件。字段是否够用？
测试的时候没有发现相关的空指针异常。
> refactor: `(*MsgContext).Notice`；初步支持跨平台发送消息

- api/conn.go
- dice/gocqhttp_helper.go
- dice/gocqhttp_helper_test.go
- dice/platform_adapter_qq.go
- main.go
相关ui调整：sealdice/sealdice-ui#29
新版本的gocq调整了签名服务的配置项，新的config.yml中的签名部分如下：
```yaml
sign-servers: 
- url: '-'  # 主签名服务器地址， 必填
key: '114514'  # 签名服务器所需要的apikey, 如果签名服务器的版本在1.1.0及以下则此项无效
authorization: '-'   # authorization 内容, 依服务端设置，如 'Bearer xxxx'
- url: '-'  # 备用
key: '114514'  
authorization: '-' 
rule-change-sign-server: 1
max-check-count: 0
sign-server-timeout: 60
is-below-110: false
auto-register: false
auto-refresh-token: false
refresh-interval: 40
```
内置生成的config.yml需要支持新gocq的配置，同时适配老版本，故同时生成两个字段 `sign-server`（旧）和 `sign-servers`（新）的配置项，如下：（部分注释已省略）
```yaml
sign-server: 'http://127.0.0.1'
key: '114514'
sign-servers:
- url: 'http://127.0.0.1'
key: "114514"
authorization: ""
rule-change-sign-server: 1
max-check-count: 0
sign-server-timeout: 60
is-below-110: false
auto-register: false …
```
> feat(gocghttp): 适配新版本gocq签名配置项

- dice/ext_coc7.go
- 失败时调用了错误的文案
- 失败时无[$t表达式文本}的问题
- 批量成长中，单技能有成功失败成长会识别不了的问题
> fix(coc): 修复批量en的一些问题

- api/js.go
- dice/builtin_commands.go
- dice/dice_jsvm.go
这个bug与UI并无关系, 因此[UI仓库的这个Issue #10](https://github.com/sealdice/sealdice-ui/issues/10)可以一并关掉
Close #207
> fix(JsExt): JS重载时,去除已删除JS对应的插件配置

- .gitignore
- dice/im_helpers.go
一个可能的用法是在自定义回复中使用正则分组捕获, 然后回复`#{DRAW-{$t1}}`
Close #216
> feat: 对于`#{DRAW-x}`写法, 支持x是`{}`包裹的表达式, 以允许其中使用变量

- main.go
> fix: change dir `./data`'s permision to 0755 from 0644

- dice/im_helpers.go
> imp: 文本长度不再包括 Base64 编码

- api/dice_config.go
- dice/builtin_commands.go
- dice/config.go
- dice/dice.go
测试中重构后的 `bot` 指令表现一致，但可能需要更多 review / 测试。
WebUI 见 https://github.com/sealdice/sealdice-ui/pull/51
close https://github.com/sealdice/sealdice-core/issues/266
> feat: 重构 `bot`，加入忽略群组裸指令支持

- api/api_bind.go
- api/backup.go
ui调整：sealdice/sealdice-ui#58
增加批量删除备份功能，默认勾选5个最近备份之外的备份，可自行调整。
close #239
> feat(backup): 提供批量删除备份接口

- api/api_bind.go
- api/conn.go
- dice/im_session.go
- dice/platform_adapter_qq.go
- dice/platform_adapter_red.go
- dice/qq_helper.go
- dice/red_helper.go
- dice/utils_email.go
- main.go
- tray_windows.go
> feat(red-protocol): red 协议的适配

- dice/dice_jsvm.go
resolve #312
ui调整：sealdice/sealdice-ui#74
> feat(js): 错误的js脚本也返回给前端，便于进行删除

- dice/platform_adapter_dodo.go
> feat: dodo card message

- dice/im_session.go
【没有经过测试：测试条件不允许】
另：这个功能似乎有可能造成 dc-like 平台因为一个频道长期不用，导致骰子从服务器退出？
> fix: 自动退群时发送通知

- dice/builtin_commands.go
> chore: 重构 ban 指令

- dice/platform_adapter_gocq_actions.go
- dice/platform_adapter_http.go
- utils/split_text.go
阈值减小到2000字节(约667汉字)
并且在指令测试页面加入一个阈值更小(300字节)的切分,以供展示效果
Issue #234
> feat: 减小QQ平台长文本切分阈值,调整切分逻辑

- dice/builtin_commands.go
- dice/cmd_parse.go
- dice/config.go
- dice/im_helpers.go
- dice/im_session.go
- dice/platform_adapter_official_qq.go
1. 完善官方 qq bot 频道私信部分
2. 由于频道中发送超过3条私信且未获得回复时，禁止再次发送私信，而这会让发送超过3条无响应私信的用户一直在等待回复，无法再向骰子发送任何私信。故增加一个 .stm (send to me) 命令，允许在频道中向骰子发送该命令，让骰子主动发送私信打破锁定。
> feat(official-qq): 完善官方 qq bot 频道私信部分，并增加 .stm 命令用于恢复私信

- dice/cmd_parse.go
- dice/ext_coc7.go
- dice/im_session.go
- dice/utils.go
1. official qq频道无法响应涉及代骰的指令
2. official qq频道，rav 指令识别出错，认为第一个玩家是骰子本身
> fix(official-qq): 修复official qq频道中的一些问题

- api/api_bind.go
- api/helpdoc.go
- dice/builtin_commands.go
- dice/dice_help.go
支持配置帮助文档分组的别名，在按组搜索时可映射。如 `DND` 可增加别名 `dnd5e`，增加后 `.find #DND xxx` 与 `.find #dnd5e xxx` 均可限制仅搜索 `DND` 分组下的条目。
ui调整：sealdice/sealdice-ui#110
> feat(helpdoc): helpdoc 支持分组别名

- dice/im_helpers.go
- dice/im_session.go
在 MsgContext 中添加 SpamCheckGroup 和 SpamCheckPerson 两项，在同一上下文中若值为 true，将不会再检查是否刷屏并消耗令牌。
> fix: 修复单次触发多条回复时，每次都检查刷屏

- dice/im_session.go
> fix(session): 自动清群发送告别语后等待3秒,避免退群过快导致消息发不出

- dice/builtin_commands.go
如图所示，是一个逻辑问题
原本的熔断机制，即 
与“忽略裸指令”选项绑定在了一起
修复如下
> fix: 修复了当开启'忽略.bot裸指令'时，@其他人进行.bot会进行响应的问题

- dice/ext_coc7.go
修改要点是：在初步判定检定成功或失败时，不能根据技能值，而是根据调整过的成功率
Issue #525
> fix(CoC): 修正带难度等级时大失败判定条件

- dice/ext_coc7.go
群里@梅花落 发现的BUG，人刚好在电脑旁，故顺手修了一下。寻思就改了一个字而已，也没啥必要提issue（
> 修正coc7代码文件中“人际依赖”描述的错字。

- dice/ext_coc7.go
现在 `$tD100`, `$t判定值`, `$tSuccessRank` 等变量会在生成结果文本之前赋值
Close #548
> fix(CoC): 调整`ra`指令的变量赋值顺序

- dice/dice_jsvm.go
新增一个 `setPlayerGroupCard` 函数直接将 go 的 `SetPlayerGroupCardByTemplate` 暴露出去。
另：现在已有一个 `applyPlayerGroupCardByTemplate` 函数是通过修改自动设置模板来设置群名片。
没有经过测试。 
Close #543
> feat(JS): 支持JS插件中直接修改群名片

- .github/workflows/build.yml
- .github/workflows/test_and_lint.yml
使用 Node.js 16 的 actions 被 github 弃用，升级到使用 Node.js 20 的版本。
> ci: upgrade actions

- dice/builtin_commands.go
- dice/dice_ban.go
- dice/dice_jsvm.go
- dice/im_session.go
- dice/platform_adapter_gocq.go
- dice/platform_adapter_walleq.go
imp: 修改 `BanListInfo.GetByID()` 的返回值，现在它还会返回是否存在的 bool 作为第二个返回值
> fix: 修复 JS API `seal.ban.getUser()` 空指针时报错的问题

- dice/platform_adapter_gocq.go
原因：拉格兰目前会发送错误的记录，其Userid和SelfId都指向自己。
加了一个简单的判断忽略这种情况。
Close #582
> fix(adapter): 修正拉格兰环境下会给自己发送加群记录的BUG

- dice/ext_dnd5e.go
由于未修改 PEG 定义，掷骰表达式中尚不支持 `r d20 優勢`
Issue #551
> imp(dnd5e): rc 指令中支持使用繁体的`優勢,劣勢`

- dice/dice_jsvm.go
- dice/dice_jsvm_test.go
- go.mod
- go.sum
支持为 JS 插件指定依赖，并可使用满足 [SemVer 规则](https://semver.org/lang/zh-CN/) 的语法限制依赖版本。
```
// @depends JustAnotherID:A
// @depends JustAnotherID:B:1.2.3  // 指定特定版本
// @depends JustAnotherID:C:^1.2.0 // 兼容版本，详见 SemVer
```
Related sealdice/sealdice-core#608
> feat(JS): JS 插件支持指定依赖以及版本

- dice/dice_jsvm.go
goja 从某一版本开始似乎将 console 分为 `node:console` 和 `console` 两个模组，其中前一个只会在控制台输出固定格式的文本，不会采用定义的 Printer。
closes #616
> fix: 修复 JS 中 console 不能使用的问题

- dice/dice.go
- dice/dice_jsvm.go
参考了 #649
这项功能用于指定海豹的**插件兼容版本**，你可以理解为最低海豹版本。
插件作者只需在插件 UserScript 部分，填写字段：
```
// @sealVersion 1.4.5
```
这代表插件可以至少在海豹的1.4.5的兼容版本可用，通常来说2.0之前都是被兼容的。
1.4.5的兼容版本，意思是除了1.4.5版本之外，可能是更高的版本。比如1.5.0等，只要原本的插件API不做修改，可以一直兼容。
当失去版本兼容性时，插件会被自动禁用。
如果出于某些原因，你不信任海豹官方设定的插件兼容版本，只希望自己的插件运行在特定版本，可以这样写：
```
// @sealVersion =1.4.5
```
这样会将海豹约束在 1.4.5 版本，任何高于或低于此版本的海豹，都不能加载你的插件。
如果你想要制定一个范围，那么可以这样写：
```
// @sealVersion >=1.4.5, <1.5.0
```
或者
```
// @sealVersion >=1.4.*
```
特别注意的是，dev版本和主版本不是一回事，例如说：
```
// @sealVersion >=1.4.5, <1.6.0
```
这个版本号不能被 1.5.0-dev 所加载，如果你希望你的插件在dev和正式版都可用，你可以写：
```
// @sealVersion 1.4.* || 1.4.*-dev
```
更多写法，请参考 semver 标准
> feat: js插件元数据增加海豹版本约束字段

- dice/platform_adapter_telegram.go
1. 认为这应该是预期行为
2. 加入 ActiveTime 字段，该字段仅在 Serve 中被更新和读取，没有必要被序列化
> imp: TG 适配器忽略关闭时积压的消息

- dice/ext_log.go
> perf(Log): `log-exports` 文件名使用时间戳替换随机数

- dice/ext_exp.go
#657 相关，使用的解决方案并非是里面提到的三种，而是与.r的解决方案类似。
自测内容包括：
```
.st san-d6 # 理智 -= 1d6
.st san-1d6 # 理智 -= 1d6
.st san-1 # 理智 -= 1
.st san-力量30  # san 录入力量30
.st san#d2 # san 录入d: 2
.st x:2
.st san-x # san -= 2
.st san-x2 # san 录入 x: 2
.st san-y # san -= 0
.st &x=d100
.st san-x # san -= d100
```
> fix: 修复简化卡支持引起的 .st san-d6 问题

- main.go
这些代码在2年前的4月21日引入，版本是1.0.0
有可能是为了处理部分服务器上域名解析的偏差问题。但是最近接到反馈说存在副作用案例，在一台国外服务器上无法一边连接discord一边连接海豹api上传log。
> refactor: 删除了dns hack相关代码

- dice/platform_adapter_gocq.go
使用LLOneBot方式搭骰后，骰子受邀加入无需审核的群时，后台群组管理显示邀请人未知，且此时不会触发群受邀通知，而是直接触发成功入群通知
修复后
> fix: 修复受邀加入无需审核的群时邀请人显示未知的问题

- dice/dice_jsvm.go
- dice/ext.go
- dice/ext_coc7.go
> refactor(JS): 重置JS环境时一并清除加载的规则模板

- api/api_bind.go
- api/backup.go
- api/misc.go
- dice/builtin_commands.go
- dice/dice_backup.go
- dice/dice_manager.go
数据结构中增加一项 `autoBackupSelection`, 类型是 uint64, 为 pow2 组合
增加 body, 格式如下, 字段类型为 uint64:
```json
{
"selection": 63
}
``` 
| 内容 | 值 |
|-----|-----|
| JS(插件和数据库) | 1 |
| 牌堆 | 2 |
| 帮助文档 | 4 |
| 敏感词库 | 8 |
| 人名数据 | 16 |
| 图片资源 | 32 |
--- 
Close #758
> feat(Backup): 增加可选的额外备份内容

- dice/verify.go
调整后可在 https://seal-verify.justanotherid.com 进行海豹码的验证
> fix: 调整生成海豹校验码时序列化字段类型

- dice/platform_adapter_lagrange_helper.go
bug：内置客户端启动时，ws正向连接地址与内置客户端已写好的配置地址不符，两者无法正常连接
解决方案：每次LagrangeServe时应读取已有配置文件中的Port值，如果用户胡乱更改lagr配置文件导致port读取失败，直接覆写一份新的。
> fix: ws正向连接地址与已生成的内置客户端配置不符

- dice/platform_adapter_gocq.go
- main.go
ServeQQ应当由LagrangeServe登录成功后进行调用，而不是还未登录成功就开始尝试ws正向连接。
问题复现：用户在已添加“内置客户端”账号后，重启核心，在内置客户端还未登录成功时，核心已经开始尝试正向连接，导致有时内置客户端登录成功前已经耗尽尝试次数。
> fix: 内置客户端在未登录成功前已开始尝试ws正向连接

- dice/ext_log.go
> fix: 修复 `.sn` 指令中存在的重复 `.sn dnd` 说明

- dice/config.go
> fix(JS): 修正设置插件配置项时出错的问题 (Followup #849)

- dice/ext_dnd5e.go
Solve #902 
A mirror of #906 as requested by @Xiangze-Li
> fix(#902): .init set 后先攻列表不重新排序

- dice/cmd_parse.go
- dice/ext_dnd5e.go
- dice/ext_dnd5e_template.go
- dice/ext_exp.go
- dice/ext_fun.go
- dice/game_system_template.go
- dice/rollvm_migrate.go
Fix #894
Fix #900
Fix #917
Fix #920
Close #893
修正死亡豁免表达式显示
修正seal.format对于dnd5e模板计算属性的错误显示
修正rc代骰问题
增加被察到模板
> fix(dnd5e): 修正rc代骰，以及死亡豁免文案等问题

- dice/builtin_commands.go
- dice/ext.go
- 添加 `func (d *Dice) ClearExtStorage(name string) error`，删除 `data/default/extensions/{name}/storage.db`
- 添加 master jsclear 命令，执行上面的函数，不可删除内置插件数据
> feat: 添加 master jsclear 指令清除插件存储

- dice/config.go
> fix(JSConfig): 修复 未被使用的配置项不会被标记为Deprecated

- dice/cmd_parse.go
> fix: 修正CQAT正则会导致AT不生效的问题

- api/resource.go
> fix(resource): 修复在windows上资源列表展示的路径是反斜杠的问题

- dice/config.go
- dice/dice.go
- dice/model/attr.go
- dice/model/group_info.go
- dice/utils.go
- go.mod
- go.sum
原config.go的Save函数，有一个//TODO: 这里其实还能优化。
在某次检查时，我发现：此处的'AttrGroupSave"函数会被大量调用。而AttrGroupSave函数是一个插入语句，这意味着每30秒，就可能有大量插入语句执行。
在诺扣提公骰的数据环境下，每次自动保存将会插入6000+数据。
根据上面的代码，以及和木落的沟通，确认此处缺少检查语句，此处逻辑应当是仅更新的才会被插入。由于并不清楚此处的更新逻辑，且150该代码重构理论该问题已经消失，采用如下方案：
本PR采用了维护一个哈希表的方式，通过每次检查要被保存的数据哈希值是否变动，从而确定是否应该插入，从而部分解决了问题。
部分解决指：
- 没有解决数量较大时，不是批量插入，而是一条一条插入带来的性能问题
- 没有解决仅更新的数据不应当存放在对应结构体
> fix: 采用哈希表的方式修正自动保存重复插入未变动的数据

- dice/builtin_commands.go
- dice/dice_help.go
曾经在小鸟处遇到过TextMap并发，导致panic的问题。故切换成SyncMap。
注：已经在小鸟处稳定测试无异常
注2：但是现在提交的代码并非从小鸟处直接粘贴的，而是根据原理重新改的，由于电脑不同，未能进行测试。
> fix(Doc): 修正偶发情况下，帮助文档的TextMap并发导致的panic闪退问题。

- dice/ext_log.go
> fix: 通过将日志上传改为异步改善竞争问题

- dice/platform_adapter_gocq.go
如题。试图解决大量解散群聊但后台不删除的情况。这应当不影响日志相关。
> fix: 在解散群聊的时候，同步dismiss的操作去除群账号链接

- dice/builtin_commands.go
> fix(Helpdoc): 使用帮助文档分组的别名时标题搜索失效

- dice/builtin_commands.go
原因是在将分组名从搜索关键字里去除时没有正确地套用别名
(cherry picked from commit d49738336822ceda2d06d64ea9a63c1839350105)
Signed-off-by: Xiangze Li <lee_johnson@qq.com>
> fix(Helpdoc): 使用帮助文档分组的别名时标题搜索失效 (Cherrypick #1120)

- dice/ext_dnd5e.go
- dice/ext_exp.go
- dice/rollvm_migrate.go
Fix #1056
Fix #1122
上为改前，下为改后
Fix #1091
> fix: 修复了d3 测试的输出异常，st代骰的输出异常，以及dnd rc改为小写以增强视觉一致性

- dice/im_session.go
- dice/model/db.go
- dice/model/log.go
Fix #1135
log_items 行为具体解释一下：
如果当前已经存在这个表，且使用sqlite时，会对比现存表和新表，如果发生列的类型或者数量区别，都会调用 AutoMigrate，否则跳过。
特别的，对于 is_bot 这一列，bool 类型和 numeric 类型都算通过
> fix: 修复启动时数据库迁移和回收导致的过长启动时间，并对log_items做了特殊处理。同时修复jsReload后插件默认关闭的问题

- dice/config.go
- dice/dice.go
- dice/dice_config.go
- dice/dice_config_default.go
- dice/verify.go
- utils/public_dice/sdk.go
目前通过这种方式使用：
在serve.yaml中，将publicDiceEnable设置为true
```yaml
publicDiceEnable: true
publicDiceId: ""
publicDiceName: ""
publicDiceBrief: ""
publicDiceNote: ""
publicDiceAvatar: ""
```
配置中的publicDiceId会在第一次启动后获得，相当于一个密钥。
同时在同一个文件靠上方的endPoints中，将你想要进行公开登记账号的isPublic设置为true，例如：
```
endPoints:
- baseInfo:
id: b0a2972b-2d8e-4241-805e-7a62beeaf5de
nickname: 木落的测试机器人
state: 1
userId: KOOK:12345
enable: true
isPublic: true
```
这样这个号就会出现在公骰列表，未标记的号不会出现。
启动后20s后会进行一次上报，之后每3分钟进行一次刷新。服务器一般来说刷新间隔是30s，因此极端情况下目前需要1分钟才能看到账号登记。
骰子关闭之后，没有继续刷新的账号会在一小段时间后被标记为离线，而在大概一小时后从列表中消失。
> feat: 公骰列表后端基础功能

- dice/config.go
> fix: 解决插件配置项反序列化类型出错问题 (fix #1142)

- api/conn.go
- api/utils.go
- dice/platform_adapter_gocq.go
- dice/platform_adapter_lagrange_helper.go
- main.go
前端部分：https://github.com/sealdice/sealdice-ui/pull/245
手册部分：https://github.com/sealdice/sealdice-manual-next/pull/301
解决：
1、https://github.com/sealdice/sealdice-android/issues/36
2、m芯片mac用户无法使用内置协议端
~~**保留代码，先close，寻求更好的解决方案**~~
**这是目前唯一有效方案**
新版gocq部分已经修改完（包括快捷启动、签名注入）仓库：https://github.com/sealdice/go-cqhttp-lagrange 可以在Action里面下载试用
这里可以直接试用打包好的https://github.com/Fripine/sealdice-build/actions/runs/12094669312
> feat: 添加内置gocq(新版)

- main.go
> fix: 修正在无env文件时会导致崩溃的问题

- dice/model/group_info.go
这是上一个修复的修复，使用First在查询不到数据时会提示报错的问题。
> fix: 修正使用First的情况下，查询会导致提示报错的问题

- api/dice_public.go
- dice/platform_adapter_lagrange_helper.go
- dice/version.go
1、copy函数的dst要提前分配好空间，之前忘了（这个copy函数我根本没用过，看例程漏看了注意项那一行），现在我选择用append
2、升级版本号
3、公骰设置保存至配置文件
> fix: 修复SignInfo空切片的问题

- dice/im_session.go
- dice/model/database/cache/gormcache.go
- dice/model/database/mysql.go
- dice/model/database/pgsql.go
- dice/model/database/sqlite.go
- dice/model/database/sqlite_cgo.go
- dice/model/db.go
- dice/model/engine_interface.go
- dice/model/engine_mysql.go
- dice/model/engine_pgsql.go
- dice/model/engine_sqlite.go
- go.mod
- go.sum
如题，otter缓存: https://github.com/maypok86/otter;
基于对缓存和并发数据结构的研究，Otter 是 Go 最强大的缓存库之一。 Otter还借鉴了其他语言（例如[caffeine](https://github.com/ben-manes/caffeine) ）设计缓存库的经验。
同时，我现在以context创建data,logs,censor的gorm.DB，从而可以在缓存清理时，针对data/logs/censor的不同进行缓存清理，这样能增加缓存命中率。
注：由于sqlite是物理分割的，所以这个优化似乎只对PG和MYSQL有效。
另外针对Init，对应的代码要求传入context，为以后可以使用超时关闭数据库的context做准备(待定，现在反正直接传递了context.Background()）
> refactor: 使用otter缓存替代buntdb，并借助context对除SQLITE以外的数据库进行细粒度缓存

- dice/ext_dnd5e.go
> fix: 修复 `.init set` 无法添加新单位的问题

- dice/ext_log.go
第一次弄，之前把主分支推过来了，后来要修别的时发现不太对劲，就关闭重推了一下。
如题，解决了[#1222](https://github.com/sealdice/sealdice-core/issues/1222)的问题（）
自己测了下应该没啥问题……
然后我发现.nn命令名称超长时也没有报错……以后再说。
> fix: 修正使用sn设置插件内名片模板时，名片模板错误和名片超长时显示设置成功但未成功的问题（增加sn命令default分支内的错误处理）。

- dice/dice_attrs_manager.go
- dice/service/attrs_new.go
经过检查，强怀疑和两处错误有关：
1. 清除未释放的数据时，判断逻辑失误。判断是否为未释放的数据时，其时间写反，导致判断永远不生效。
2. DoUpdates行为异常。原本写法下，会每次取表内的数据，将表内的数据更新为表内的数据。GPT表示无法通过调整GORM来解决这个问题，且发现可能关联的，仍然打开的ISSUE如下：https://github.com/go-gorm/gorm/issues/6047
上述两个问题合并，疑似刚好拼凑出了特别情况：数据落盘后并未被正确清理，造成数据卡数据一直驻留在内存中，并在重启后丢失
目前考虑的修复思路为：
修正时间写反的问题，保证判断能正确生效。
将原本的批量逻辑，改为先区分插入和更新，然后分别进行处理，插入采取批量插入，更新采取顺序按条更新。
此处为对应PR。（或许事实上还是没找到原因在哪儿……）
> fix: 尝试修正批量入库的无法正确落盘问题

- dice/ext_dnd5e.go
- dice/im_session.go
- dice/rollvm_migrate.go
- model/group_info.go
> fix: 修复 DND5e rc 使用技能别名进行检定时会展示原始函数的问题

- api/api_bind.go
- api/dice_config.go
- api/utils.go
- dice/dice_manager.go
- 将 AccessTokens 从 map 改为 SyncMap，提高并发安全性
- 在修改 UI 密码时清除所有现有访问令牌，强制重新登录
- 更新访问令牌的存储和验证方式，提高效率和安全性
Close #1303
> feat(security): 修改密码之后现有会话立即失效

- .golangci.yml
- .golangci.yml.old
将 lint 配置升级为最新版格式（部分旧文件中的 rules 已经作废）
> chore(lint): update golangci-lint config

- dice/ext_log.go
Close #1347 
仿照私聊中 log on 的判断逻辑对 log export 和 log get 进行了私聊群聊区分修复，以免出现导出错误数据的情况
> 对log get和log export私聊群聊判断进行了修复

- dice/builtin_commands.go
> fix: nil ptr deref when setting default dice with no player

- dice/rollvm_migrate.go
Close #1369 
对问题的准确描述应该是：当熟练加值存在小数时（如 `*0.5` 或 `*1.5`），不论舍入后的计算结果是否是整数，都会显示异常。
非常好绕来绕去，要不是 go 能步进追三方库的调用绝逼查不出来
> fix(DnD): 当熟练系数是浮点数时检定结果显示异常

- dice/im_session.go
> feat: 允许插件的暗骰被录入log
