dice/ext_fun.go
=> chore: make lint happy

api/api_bind.go, dice/dice.go, dice/platform_adapter_kook.go, go.mod, main.go
=> fix: 修复ui无法显示异步发送消息的问题

dice/dice.go, dice/ext_log.go, dice/gocqhttp_helper.go, dice/im_session.go, dice/platform_adapter_kook.go, dice/platform_adapter_qq.go
refactor: 将adapter与数据库操作解藕
fix: 部分情况下分离部署表现异常的问题
=> feat: 添加OnMessageDeleted接口

dice/cq_helper.go, dice/dice.go, dice/platform_adapter_discord.go, dice/platform_adapter_kook.go, dice/platform_adapter_qq_actions.go
=> feat: 支持发送base64图片

api/conn.go, dice/platform_adapter_qq.go
issue #135 
ui修改：sealdice/sealdice-ui#16
=> feat: 添加分离部署gocq的账号时，支持指定access token

dice/platform_adapter_discord.go
不再使用 gorilla/websocket 默认的 Dialer
=> fix: dg 使用代理时会代理 kook

api/api_bind.go, api/news.go, api/utils.go, dice/config.go, dice/dice.go
ui修改：sealdice/sealdice-ui#23
记录已阅读过的新闻信息md5值，在有变化时支持小红点提醒
=> feat(news): 海豹新闻支持提醒和已读

.github/workflows/build.yml, .github/workflows/test_and_line.yml
自动打包多平台开发版本：
- linux/amd64
- linux/arm64
- windows/386
- windows/amd64
- darwin/amd64
- darwin/arm64
=> ci: 增加构建工作流，自动打包开发版本

dice/ext_log.go
=> fix(sn): 群名片超长时返回提示信息

dice/dice.go, main.go
chore: change build name
fixes sealdice/sealdice-android#20
=> fix(android): 修复于安卓运行时的时区问题

api/api_bind.go, api/helpdoc.go, api/utils.go, dice/builtin_commands.go, dice/dice_help.go, go.mod
- 增加帮助文档相关接口，支持对应的ui
- 按文件夹对帮助文档分组，.find支持搜索指定分组下的文档
ui调整：sealdice/sealdice-ui#27
close #52
=> feat(helpdoc): 帮助文档支持分组搜索，并提供ui界面支持

dice/model/db.go, main.go, migrate/convert_logs.go, migrate/log_item_fix_type.go
原类型为INTEGER, 隐式类型转换可能使Log与消息不一致, 改为TEXT
提供了migration代码，可以自动修复老数据
close #172
=> fix(log): log_items.message列数据类型错误

api/group.go, dice/builtin_commands.go, dice/dice.go, dice/dice_ban.go, dice/im_session.go, dice/platform_adapter_qq.go, dice/platform_adapter_walleq.go
这是为了解决存在多个EndPoint时存活消息将重复数次的问题
=> fix(Notice): Notice增加跨平台开关参数，存活消息禁止跨平台发送

dice/config.go, dice/ext_log.go
- log on → 如果当前Log已在记录 → 报错
- log new → 如果已经Log on/有未结束的Log → 报错
- 去除了使用 `log new <name>` 强行新建Log的逻辑
Close #50
=> feat(Log): 重复log on/log new报错

dice/builtin_commands.go
支持序号代替角色名的子指令有`pc load`, `pc tag`, `pc untagAll`, `pc del/rm`等4个.
Close #159
=> feat(角色管理): pc list增加序号, 之前要求指定角色名的pc指令支持按序号操作

dice/ext_dnd5e.go
=> feat(dnd): .ri 支持优势劣势

dice/model/db_utils.go, go.mod, go.sum, main.go, migrate/log_item_fix_type.go, utils/spinner/spinner.go
1. 在处理旧数据过程中加强提示, 避免用户误关程序而导致VACUUM不能完成
2. 提供一个程序flag `--vacuum`, 调用后对两个db文件进行整理瘦身, 用来处理当前已经胖起来的数据库
=> 数据库文件发胖问题解决

dice/builtin_commands.go
=> feat(master): 增加.master reload deck/js/helpdoc命令支持相关系统重载

api/dice_config.go
=> feat(管理后台): 邮箱密钥设定后显示为`******`以免泄露

api/api_bind.go, api/story_log.go, dice/model/log.go
=> feat(story): 增加跑团日志和日志行的分页查询接口

api/story_log.go, dice/ext_log.go, dice/model/log.go
上传时先检查DB中记录的URL和上传时间, 如果有URL且上传时间晚于更新时间, 直接返回存储的URL
否则, 执行上传, 得到的URL落库
Close #61
=> feat(Log): Log未更新时不重复向服务器上传

api/dice_config.go, dice/config.go, dice/dice.go, dice/dice_jsvm.go
=> fix(JsExt): 不再删除插件配置,而是不返回未加载插件的配置给前端

api/dice_config.go, dice/builtin_commands.go, dice/config.go, dice/dice.go, dice/ext_coc7.go, dice/ext_fun.go, go.mod, go.sum
WebUI 的 pr 见 https://github.com/sealdice/sealdice-ui/pull/46
close https://github.com/sealdice/sealdice-core/issues/126
=> feat: 增加两个设置项，用于骰点上限和 COC 制卡上限

api/api_bind.go, api/censor.go, dice/censor/censor.go, dice/dice.go, go.mod, go.sum
=> feat(censor): 支持下载敏感词库模板，并调整默认的敏感词拦截模式设置

dice/dice.go, dice/im_session.go
在设定为Master的群组中可以自由使用高权限命令, 等价于群成员全员均有Master权限
但群成员在Master群之外仍然受个人Master权限管制
Close #267
=> feat: 支持群组作为Master

api/dice_config.go, dice/builtin_commands.go, dice/config.go, dice/dice.go
Re-pull
WebUI (merged) https://github.com/sealdice/sealdice-ui/commit/71d23ace351a3491f73098dbd740c4b3080e5314
close https://github.com/sealdice/sealdice-core/issues/266
=> feat: 重构 `bot`，加入忽略裸指令支持

api/conn.go, dice/config.go, dice/im_session.go, dice/model/db.go, dice/model/endpoint_info.go
=> feat(Endpoint): EP统计数据持久化到数据库,实现删除后重新添加 继承之前的数据

api/conn.go, dice/platform_adapter_telegram.go, dice/telegram_helper.go
Close #274
UI PR: https://github.com/sealdice/sealdice-ui/pull/52
=> feat(endpoint): add http proxy support for Telegram

dice/utils_email.go
=> feat(Mail): 在邮件通知标题中添加骰子名称

api/api_bind.go, api/deck.go, dice/dice_jsvm.go, dice/ext_deck.go, dice/utils_ext.go, go.mod, go.sum
=> feat(deck): 牌堆可从远程获取更新，并新增toml牌堆格式

api/api_bind.go, api/js.go, dice/dice_jsvm.go, dice/ext_deck.go
=> feat(js&deck): 支持js插件配置更新链接，修复toml牌堆的一些问题

api/api_bind.go, api/dice_config.go, dice/builtin_commands.go, dice/im_session.go, dice/platform_adapter_qq.go, dice/utils_email.go
ui: sealdice/sealdice-ui#57
close #242
=> feat(mail): 支持发送测试邮件

dice/platform_adapter_discord.go
=> revert(discord): 回滚Discord入群致辞

dice/builtin_commands.go
=> feat(ban): 提供.ban query命令查询指定用户黑名单情况

api/conn.go
=> feat(conn): 删除endpoint时先禁用，防止出现链接未断开的问题

api/ban.go, dice/dice_ban.go, dice/im_session.go
close #224
ui sealdice/sealdice-ui#60
=> feat(ban): 提供黑名单立即退群功能

api/api_bind.go, api/conn.go, dice/gocqhttp_helper.go, dice/gocqhttp_helper_appversion.go, dice/platform_adapter_qq.go, main.go
=> feat(gocqhttp): 内置gocq支持切换协议版本

dice/gocqhttp_helper.go
=> feat(gocqhttp): 内置gocq快速启动修复

api/api_bind.go, api/ban.go, dice/dice_ban.go
ui：sealdice/sealdice-ui#67
close #252
=> feat(ban): 增加黑白名单导入导出功能

api/dice_config.go, dice/config.go, utils/rate.go
=> fix: coc制卡上限和刷屏频率配置无法正确加载

dice/platform_adapter_discord.go
=> feat(discord): embed message 格式

update_updater.go
=> chore(update): 更新升级器版本

api/backup.go, dice/builtin_commands.go, dice/dice_backup.go, dice/dice_manager.go, utils/files.go
=> feat(Backup): 自动备份清理-后端

dice/builtin_commands.go, dice/dice.go, dice/dice_jsvm.go, dice/ext.go, dice/ext_fun.go, dice/ext_log.go, go.mod, go.sum
感觉有一定危险, 等发新版本之后再合到测试版
Issue #302
=> feat(ext): 扩展支持设置别名

dice/builtin_commands.go
=> fix(CmdBan): `ban rm user x`当x从未有记录时panic

api/api_bind.go, dice/config.go, dice/dice.go, dice/dice_jsvm.go, go.mod, go.sum
Closes #63 
目前只是一个构想，先提一个draft看看有没有建议
=> feat(JsApi): 插件配置项

dice/dice_censor.go, dice/im_helpers.go, dice/im_session.go
=> feat(censor): 修复敏感词拦截的一些问题

api/dice_config.go, dice/dice.go, dice/im_session.go
=> feat: 自动清理不活跃群聊

dice/config.go
=> fix: 黑名单的`使用时立即退出群`配置无法正确持久化

api/dice_config.go, dice/builtin_commands.go, dice/cmd_parse.go, dice/ext_deck.go, dice/ext_fun.go
Close #301
也修改了若干处 `CmdExecuteResult` 中 `Solved` 字段, 从 `false` 改为 `true`. 这是因为, false会在日志里留下"忽略指令"记录, 这是不符合实际情况的.
=> feat: 放开`制卡上限`和`轮数上限`的限制, 并允许`drl new`创建大于轮数上限的骰池

dice/ext_log.go, dice/platform_adapter.go, dice/platform_adapter_dingtalk.go, dice/platform_adapter_discord.go, dice/platform_adapter_dodo.go, dice/platform_adapter_gocq_actions.go, dice/platform_adapter_http.go, dice/platform_adapter_kook.go, dice/platform_adapter_minecraft.go, dice/platform_adapter_red.go, dice/platform_adapter_telegram.go, dice/platform_adapter_walleq.go
feat: 实现 `Dodo` 平台的 `QuitGroup()` 和 `SetGroupCardName()`
=> imp: 重构 `SetGroupCardName()`

main.go
=> feat(ui): ui 资源启用 gzip 压缩

dice/platform_adapter_dodo.go
=> fix: 修复 `DoDo` 平台发送私聊消息的问题

dice/builtin_commands.go
重构是以减少嵌套为主旨出发的。未能进行测试，需要 review 一下逻辑是否与原来的代码等价。
=> chore: 重构 `master` 指令

dice/ext_dnd5e.go
没有处理 `ri` 或 `init set` 造成先攻列表变化的情况: 根据群友指出, 这种行为是规则书未列出的, 视为 UB.
Close #423
=> fix(DnD): 修复从先攻列表删除单位导致当前单位错乱

dice/config.go
=> fix(config): 初次启动时配置项默认值

dice/im_session.go
=> fix(Session): 将自动清群的逻辑补充至与其他退群一致

dice/platform_adapter_gocq.go, dice/platform_adapter_gocq_actions.go
=> feat: 允许协议中任意的Echo类型，以适配shamrock

dice/config.go, dice/im_session.go
=> feat(Session): 自动清群不清理信任白名单的群

dice/config.go, dice/im_session.go
=> feat(Session): 自动清群退出时发送告别语

dice/platform_adapter_red.go
=> fix(red-protocol): 修复 red 协议支持由于并发写入 ws 导致的崩溃问题

dice/im_helpers.go, dice/im_session.go
closes https://github.com/sealdice/sealdice-core/issues/466
See also: https://github.com/sealdice/sealdice-core/issues/228
=> imp: 将刷屏检测作为单独函数并加入 ReplyToSender 等

dice/config.go, dice/ext_log.go
=> feat(Log): 允许重复`log new`,`log end`使用自定义文案

dice/platform_adapter_http.go, main.go
=> refactor: `HttpAdapter` 内容补全

dice/ext_log.go
=> fix(sn指令): 修复插件定义的群名片模板无法自动更新

dice/dice.go, dice/ext_log.go, dice/im_session.go, dice/model/log.go, dice/platform_adapter.go, dice/platform_adapter_dingtalk.go, dice/platform_adapter_discord.go, dice/platform_adapter_dodo.go, dice/platform_adapter_gocq_actions.go, dice/platform_adapter_http.go, dice/platform_adapter_kook.go, dice/platform_adapter_minecraft.go, dice/platform_adapter_official_qq.go, dice/platform_adapter_red.go, dice/platform_adapter_sealchat.go, dice/platform_adapter_slack.go, dice/platform_adapter_telegram.go, dice/platform_adapter_walleq.go
- 向 PlatformAdapter 添加 EditMessage 和 RecallMessage 方法
- 为 KOOK 和 Discord 适配器实现上述方法
- 向 IMSession 添加 OnMessageEdit 事件
close #501
=> feat: 初步实现消息修改方法和事件

dice/config.go
=> refactor(JS): 插件配置项 `plugin-configs.json` 序列化时加入缩进和换行

dice/platform_adapter_telegram.go
=> 修复 Telegram 适配器会引起进程崩溃的问题

dice/builtin_commands.go, dice/ext_coc7.go, dice/ext_dnd5e.go, dice/ext_fun.go
=> feat: 为部分指令添加help 

dice/config.go
=> fix(JS): 修复 JS `getIntConfig()` 会报错的问题

dice/dice_ban.go, dice/dice_jsvm.go
=> feat(JS): 添加黑名单相关接口

dice/dice_jsvm.go
=> fix(JS): 黑名单相关接口使用新的 Config

api/conn.go, dice/model/db_init.go, dice/platform_adapter_official_qq.go, dice/platform_adapter_official_qq_helper.go
close: https://github.com/sealdice/sealdice-core/issues/530
=> fix(OfficialQQ): 不能“只在频道中使用”

api/dice_config.go, dice/config.go, dice/dice.go, dice/im_session.go
Related PR sealdice/sealdice-ui#152
Close #568
=> imp(Session): 一个更合适的自动退群排期模式 (#578)

dice/config.go, dice/ext_log.go
=> feat(Log): 在`log end`和`log halt`执行环境添加变量`$t记录名称`

.gitignore, dice/builtin_commands.go
在 KooK 和 TG 测试正常。由于缺少测试机，没有在 QQ 测试。
Close #373
另：修改 gitignore 以隐藏 `.vscode/launch.json`
=> feat(Send): 支持Master群组接收`send`消息

dice/ext_deck.go
对加载流程进行了少量优化，主要是基于文件后缀做更强的判断，但基本上是等价的。
Issue 610
=> refactor(Deck): 牌堆文件加载的错误记入日志,稍微优化流程

dice/ext_deck.go, go.mod, go.sum
ui 调整：sealdice/sealdice-ui#160
=> feat(Deck): json 牌堆支持尾逗号和注释的扩展语法

main.go, migrate/v144_remote_old_helpdoc.go, update.go, utils/crypto/sha256.go
Ref sealdice/sealdice-builtins#13
=> feat(Migration): remove `蜜瓜包-怪物之锤查询.json` for new helpdoc

dice/ext_deck.go, dice/platform_adapter_walleq_helper.go, go.mod, go.sum
=> chore: 只保留一个 toml 库

dice/ext_dnd5e.go, dice/rollvm.go
=> feat: dnd5e的豁免检定支持同义词，并添加部分同义词

dice/platform_adapter_official_qq.go, dice/platform_adapter_official_qq_helper.go
playground:
https://go.dev/play/p/u5jOjeOph2_r
=> feat: 在QQ官方API的发送内容中，将链接进行过滤，以防止发不出来

dice/platform_adapter_cqcode_helper.go, dice/platform_adapter_gocq_actions.go
需要 @PaienNate 确认修改内容。
Close #629
=> fix(Adaptor): 调整`[img:X]`的替换模式, 适配Windows发送

api/censor.go, dice/model/censor_log.go
UI 调整：sealdice/sealdice-ui#163
Close #602
=> feat(censor): 完善拦截日志分页查询接口

api/api_bind.go, api/conn.go, dice/im_session.go, dice/platform_adapter.go, dice/platform_adapter_cqcode_helper.go, dice/platform_adapter_qq_helper.go, dice/platform_adapter_red.go, dice/platform_adapter_satori.go, dice/platform_adapter_satori_entity.go, dice/platform_adapter_satori_helper.go, dice/utils.go, main.go, utils/satori/element.go
ui 调整：sealdice/sealdice-ui#162
Ref #321
=> feat(satori-protocol): 增加 satori 协议适配

api/story_log.go, dice/model/log.go
UI 调整：sealdice/sealdice-ui#166
Close #545
=> feat(Story): 跑团日志分页查询修复

api/dice_config.go, dice/config.go, dice/dice.go, dice/platform_adapter_gocq_helper.go
该功能目前只会导致负面后果而无正面效果
https://github.com/sealdice/sealdice-ui/pull/168
Close #637
=> feat(ImSession): 移除 gocq 的 风控自动重新登录

dice/platform_adapter_gocq.go, dice/platform_adapter_walleq.go
=> refactor(ImSession-OB11): 增加WebSocket连接失败的日志

api/api_bind.go, api/story_log.go, dice/dice_stroy_log.go
UI 调整：sealdice/sealdice-ui#170
Close #565
=> feat(story): 增加跑团日志备份文件管理 api

dice/ext_log.go
=> fix(Log): 补充`log`各个子指令的前缀切分

dice/im_session.go
原顺序: 骰主禁用 -> 骰子关闭 -> at别人 -> 私聊不可用
现顺序: 骰子关闭 -> at别人 -> 骰主禁用 -> 私聊不可用
Close #675
=> fix(ImSession): 修正解析指令时判断指令不应执行的响应顺序

dice/storylog/upload_v1.go
=> refactor(storylog): rename and re-doc

api/api_bind.go, api/dice_advanced_config.go, api/story_log.go, dice/config.go, dice/dice.go, dice/dice_advanced_config.go, dice/ext_log.go, dice/storylog/storylog.go, dice/storylog/upload_v1.go
对应 UI：sealdice/sealdice-ui#171，点击左上角 SealDice 8 次后开启
Close #539
=> feat(storylog): 增加高级设置，支持设置自定义跑团日志后端 

dice/builtin_commands.go
=> fix: 修复dismiss允许代骰的问题

api/api_bind.go
安卓端似乎接受 interrupt 之类的 signal 有问题，所以这里加一个接口用于主动停止
=> feat: 安卓端强制停止接口

dice/builtin_commands.go
=> imp: 在私聊中禁用 dismiss 及 bot bye

api/conn.go, dice/platform_adapter_gocq.go, dice/platform_adapter_gocq_helper.go, dice/platform_adapter_lagrange_helper.go, dice/platform_adapter_qq_helper.go
1. 修正了登录后完全不打印拉格兰输出的问题（应打印error信息）
2. 改善了有丝分裂等问题
=> imp: 改进了对拉格兰的支持

dice/config.go, dice/dice_jsvm.go
=> fix(JS): 修复 JS getIntConfig() 返回值类型报错问题

dice/config.go
=> fix(JS): 修复 JS getTemplateConfig()无法从[]interface{}断言[]string

api/conn.go, dice/platform_adapter_discord.go, dice/platform_adapter_discord_helper.go
=> feat(discord): 支持反向代理

dice/dice_help.go
=> fix(helpdoc): 修复 xlsx 格式 helpdoc 查询结果无意义字符问题

api/api_bind.go, api/conn.go, dice/cmd_parse.go, dice/im_session.go, dice/platform_adapter_lagrangego.go, dice/platform_adapter_lagrangego_helper.go, dice/platform_adapter_lagrangego_test.go, go.mod, go.sum, main.go, message/message.go
=> feat(adapter): implement LagrangeGo

dice/logger/logger.go, main.go
=> refactor: 允许设置日志等级

go.mod, go.sum
=> chore: bump LagrangeGo

dice/platform_adapter_discord.go, dice/platform_adapter_dodo.go, dice/platform_adapter_kook.go, dice/platform_adapter_lagrangego.go, dice/platform_adapter_telegram.go, go.mod, go.sum, message/message.go
=> refactor: ReplyElement

dice/platform_adapter_lagrangego.go
Chore: make config dir check earlier
=> feat(LagrangeGo): `QuitGroup()`

dice/builtin_commands.go
=> fix(cmd-PC): 禁止通过序号删除已绑定的卡

dice/config.go, dice/dice_jsvm.go
按理说是 breaking change，因为更改了 registerXXXConfig，但实际上老插件似乎不受影响？
[sealdice-ui #184](https://github.com/sealdice/sealdice-ui/pull/184)
=> feat: 为插件配置项添加简介字段

dice/ext_deck.go
=> fix(Deck): 修补删除.deck牌堆逻辑

api/reply.go, dice/ext_reply.go, dice/ext_reply_logic.go
Close #753
UI sealdice/sealdice-ui#189
=> feat(Reply): 支持文件级的执行条件

dice/dice.go, dice/im_session.go, dice/platform_adapter_lagrangego.go, go.mod, go.sum
feat: LagrangeGo private image element
=> feat(LagrangeGo): GroupJoinedEvent GroupMemberJoinedEvent

dice/dice_backup.go
=> fix(Backup): 补充备份文件

dice/im_session.go
chore: 移除意义不明的 mustLoadUser
Close #767
=> fix: 修复 OnNotCommandReceived 回调在部分情况下无法调用临时变量的问题

dice/platform_adapter.go, dice/platform_adapter_dingtalk.go, dice/platform_adapter_discord.go, dice/platform_adapter_dodo.go, dice/platform_adapter_gocq.go, dice/platform_adapter_http.go, dice/platform_adapter_kook.go, dice/platform_adapter_lagrangego.go, dice/platform_adapter_minecraft.go, dice/platform_adapter_official_qq.go, dice/platform_adapter_red.go, dice/platform_adapter_satori.go, dice/platform_adapter_sealchat.go, dice/platform_adapter_slack.go, dice/platform_adapter_telegram.go, dice/platform_adapter_walleq.go
=> feat(adapter): Message Segment Sending Interface

.github/workflows/test_and_lint.yml
合并后总用时会长一点，但是合计用时每次从约 4min 降到约 3min，应该能节省一些计费（x
=> ci: 合并 test 和 lint

dice/builtin_commands.go
=> fix(cmd-botlist): 使关闭的bot在执行botlist指令时不回复

dice/config.go, dice/dice_advanced_config.go
关联 UI：sealdice/sealdice-ui#193
=> feat(advanced-config): 高级设置页可以单独控制是否显示

api/dice.go, api/misc.go, dice/builtin_commands.go, main.go
UI 调整：sealdice/sealdice-ui#194
=> feat(upgrade): 容器模式下禁止更新

dice/dice_manager.go, go.mod, go.sum, main.go, tray_darwin.go, tray_windows.go, update.go, update_updater.go
=> fix: 修复程序清理函数可能被多次调用的问题

main.go
~~调了半天前端 `index.html` 里的设置不生效，结果居然是后端也返了……~~
=> fix(resource): 修复 CSP 导致的服务器访问时资源图片不加载问题

api/api_bind.go, dice/im_session.go, dice/platform_adapter_http.go
Ref #59，一个初步的支持，先解决有和无的问题。
关联的 UI 调整：sealdice/sealdice-ui#197
=> feat(Test): 支持 UI 指令测试页面的群聊模式

dice/dice_backup.go
=> fix(Backup): 修复插件数据库无法进入备份的问题

api/api_bind.go
=> feat(api): 支持ui识别展示模式

dice/platform_adapter_gocq.go, dice/platform_adapter_qq_helper.go
=> fix: ws正向连接禁用按钮无法生效

dice/builtin_commands.go, dice/rollvm_migrate.go, readme.md
=> fix: 修复.pc rm读取当前群名片为删除卡名的问题，以及rm/rename/tag指令角色名与群名片重名时的一些问题

api/api_bind.go, dice/config.go, dice/dice.go, dice/dice_jsvm.go
Close: #761 
前端 PR: https://github.com/sealdice/sealdice-ui/pull/214
=> feat (JS): 为插件提供定时任务 API

dice/config.go, dice/ext_dnd5e.go, dice/ext_dnd5e_template.go, dice/ext_exp.go, dice/im_session.go, dice/im_vars.go, dice/rollvm_migrate.go, go.mod, go.sum
=> imp: 改进了详情信息的显示方式，同时st-1-1的行为进行兼容修正(来自ds的更新)

dice/utils.go, migrate/v150_attrs.go
=> fix: 升级导致同群用户人物卡数据相同

dice/rollvm_migrate.go
=> fix(DnD): 修复属性豁免加值计算错误

dice/ext_dnd5e.go
=> fix(#902): .init set 后先攻列表不重新排序

dice/dice_help.go
=> fix(HelpDoc): 当一条帮助文档中引用多个其他项目时替换不正确

dice/ext_dnd5e.go, dice/ext_exp.go
=> fix: ri =d20这种语法不起效，以及.st技能相关问题

api/api_bind.go, api/utils.go
对应 UI 调整：sealdice/sealdice-ui#226
=> feat: 为 UI 提供网络质量检测 API

api/api_bind.go, api/utils.go
(cherry picked from commit 857c5a66d14400acc6aa79b4d04b3737748290b9)
=> feat: 为 UI 提供网络质量检测 API (#924)

dice/ext_dnd5e.go, dice/ext_dnd5e_template.go, dice/game_system_template.go, dice/im_session.go, dice/rollvm_migrate.go, go.mod, go.sum
=> fix(DnD): buff 数据正确进入计算, st show 中计算式显示为原始数据

api/js.go, dice/dice.go
=> 修正插件较多时，点击多次重载插件会导致的并发崩溃问题

dice/game_system_template.go, dice/im_session.go, dice/rollvm_migrate.go
=> fix(150): 修复自动退群时触发崩溃的情况

dice/ext_dnd5e.go
=> feat(DnD): init del 删除当前角色后提示下一角色或列表已清空

api/conn.go, dice/platform_adapter_lagrange_helper.go
=> feat(Lagrange): 支持设置内置拉格兰的签名版本

dice/im_helpers.go, dice/platform_adapter_gocq.go
=> fix(gocq): function GetPlayerInfoBySender returns a nil pointer in GroupPokeEvent

dice/config.go, dice/platform_adapter_lagrange_helper.go, tray_windows.go
=> imp: 拉格兰api版本迁移 & win托盘显示版本号

dice/config.go, dice/ext_log.go
=> feat(log): 为 `日志:记录_结束` 提供 `$t当前记录条数`

dice/ext_exp.go
=> fix(Log): 修复了骰点统计报错的问题

dice/ext_log.go
在原来的基础上重新改了一下，直接删除了ob help中的stat help
=> fix: 修正ob help帮助信息部分错处

dice/ext_exp.go, dice/ext_log.go
Fix #983 
理论上有衍生问题，即150以前的版本所创建的log也会报错，应该已经兼容
=> fix(log): 修复骰点统计报错

dice/im_vars.go
=> feat: 创建临时变量 `$t权限等级`

dice/im_vars.go
=> feat: `$t平台` 对 official 单独赋值

dice/dice_jsvm.go, go.mod, go.sum
对应 UI 调整：sealdice/sealdice-ui#238
=> feat(TS): 支持直接加载 typescript 脚本

dice/platform_adapter_official_qq.go, dice/platform_adapter_qq_helper.go
=> fix(OfficialQQ): 修复启动时涉及 official qq 的报错

dice/platform_adapter_gocq_actions.go
=> fix: 对CQ码指向的含有逗号的文件名进行转义，使其能被发送

dice/dice.go, dice/dice_attrs_manager.go, dice/model/backup.go
=> fix(Dice): 修复了am.logger潜在的空指针问题

dice/config.go, dice/ext_dnd5e.go
补充了对dnd5e插件下rc检定回复词的自定义，fix #551
=> 尝试为dnd5e检定添加自定义回复

utils/kratos/helper.go, utils/kratos/zap.go
突然发现有两个BUG，修正之：
1. 修正Web日志会不小心顶掉原本的zapLogger,导致后续日志调用链全豹炸的问题
2. 修正Web日志Named会不停堆叠，导致堆叠出错的BUG。
=> fix: 修正大一统日志的问题

.github/workflows/reviewdog.yml, .github/workflows/test_and_lint.yml, .reviewdog.yml
=> ci: add review dog

dice/dice_backup.go, dice/dice_manager.go, dice/ext.go, dice/platform_adapter_gocq.go, go.mod
=> fix: 修正清理备份的按时间模式不正确生效问题

dice/dice_backup.go, dice/dice_manager.go, dice/ext.go, dice/platform_adapter_gocq.go, go.sum
顺带清理冗余的日志输出
(cherry picked from commit 19c6d885fb274ffdd7dc7c51d4db86a42854fab3)
=> fix: 修正清理备份的按时间模式不正确生效问题 (Cherrypicked #1084)

utils/paniclog/redirect_stderr_windows.go
如题，某些报错情况下，日志不会被记录（好像是什么主goroutine的情况下？）
这个PR将解决该问题。
=> fix: 修正部分情况下，panic日志无法正确记录到log的问题。

go.mod, go.sum, main.go, utils/paniclog/paniclog.go, utils/paniclog/redirect_stderr.go, utils/paniclog/redirect_stderr_unix.go, utils/paniclog/redirect_stderr_windows.go
> 顺带好奇一下，John佬的cherry pick好像是选择了某个commit，这个是怎么方便的选出来的呢——
=> feat: 重定向输出panic日志到panic.log，并增加用户友好的日志模块提示。 (Cherrypicked #1067,#1087) 

api/utils.go
(cherry picked from commit 392beb46852d652ef6851ae28827492d99e9577b)
=> feat(api): 网络质量检查进行三次请求以提高结果准确性 (#1088)

dice/ext_dnd5e.go
=> fix: 先攻列表无法删除带有空格的名字的角色

dice/platform_adapter_sealchat.go
=> fix(platform): 修正sealchat错误注册wss链接的bug

utils/paniclog/paniclog.go
=> fix: 将权限调整为0644以适应容器等特殊情况。

dice/config.go, dice/dice.go, dice/dice_jsvm.go, dice/im_session.go
=> fix: js重载后指令顺序被打乱的问题

dice/ext_exp.go
=> fix: 修复因为简化卡兼容而不能正常执行.st X-(1d4+1)的问题

dice/model/db.go, migrate/v150_attrs.go
=> fix: 去除错误的制表符，解决attrs表被错误删除大量数据的BUG

dice/platform_adapter_kook.go
=> fix: 修复一些情况下可能的 panic 问题

dice/platform_adapter_telegram.go
=> fix: 修复 `TG SDK` 会向 `stderr` 输出日志的问题

dice/config.go
=> fix(Config): 使 `task:cron` 和 `task:daily` 类型的配置能够正常被加载

api/deck.go, api/js.go
涉及前端调整：sealdice/sealdice-ui#246
Fix #1146
=> feat(js&deck): 调整 JS 插件和牌堆接口中依赖 index 的 api

dice/ext_log.go, dice/rollvm_migrate.go
拆成了四个 commit，@fy0 有空的话可以仔细看看
现在 `.sn` 是只读的了
=> fix: 修复 `.sn` 指令可以修改内部变量的问题

dice/config.go, dice/platform_adapter_lagrange_helper.go
ui部分：https://github.com/sealdice/sealdice-ui/pull/247
更改部分主要为目前可用新版sign的热心群友赞助的反代地址以及版本号。
=> feat: change link of adapter-lagrange-helper-go

dice/platform_adapter_gocq_actions.go
=> feat(Adapter):使用适配器方式解析戳一戳CQ码

dice/model/engine_sqlite.go, main.go
=> fix: 修正SQLITE数据库检查会全部异常FALSE的问题

main.go, migrate/v150_attrs.go
=> refactor: 添加更友好的提示和判断，并在失败时回滚数据库处理

dice/builtin_commands.go
Related #963 属于一比一复刻了过来。
Close #961
原代码作者：Fripine.
=> fix(helpdoc): 修正帮助文档分页符无法使用的问题

dice/im_session.go, migrate/v150_attrs.go
=> fix: 修正群黑名单且未成功退群时，错误认为是用户黑名单导致炸豹的问题

api/ban.go, dice/dice_ban.go, dice/im_session.go
经过了测试，正常运行，但是不确定会不会引起其它地方什么连锁反应……前端pr #254[https://github.com/sealdice/sealdice-ui/pull/254](url)
=> feat: 添加"使用者为管理员立即退群，为普通群员仅拒绝回复"后端逻辑

api/api_bind.go, api/dice_public.go, dice/dice.go, dice/im_session.go, migrate/convert_serve.go
前端部分：https://github.com/sealdice/sealdice-ui/pull/255
比较简单的实现，就两个路由，一个拿来获取信息，一个拿来设置信息
=> feat: 公骰设置后端修改

api/helpdoc.go, dice/builtin_commands.go, dice/dice_help.go, dice/dice_manager.go, dice/docengine/bleve.go
由于指令的帮助文档在整个帮助文档加载之后加载，原本我忽略了这部分，导致指令的所有帮助文档无法进行加载。
现在修改之后，应当能正确加载。
=> fix: 修正帮助文档无法加载指令相关帮助文档的问题，并补充部分日志

dice/dice_jsvm.go, dice/im_vars.go
效果如图：
PS：这东西代码量虽然小，但是研究的时候是真费劲，翻了好半天的代码
=> feat: `JSVM` 支持读取/写入计算变量（公式）

api/api_bind.go
前端 PR：https://github.com/sealdice/sealdice-ui/pull/258
Resolve #1151
=> feat: 修改 delete_unused_config 为 delete_unused_configs，允许批量删除配置项

dice/platform_adapter_gocq.go
=> fix: 修复连接nc时，语音的CQ码没有正确给出文件路径

dice/docengine/bleve.go
=> fix: 修正docEngine精确匹配术语错误的问题

dice/ext_dnd5e.go
=> fix: 修复在先攻列表中添加项目可能导致当前角色偏移的问题

dice/ext_dnd5e.go
=> fix: 修复无法正确扣除 buff hp 的问题

dice/dice.go
很难想象这个 bug 出现了这么久但是没有任何人提 issue
=> fix: 修复 QuitInactiveThreshold 被调至 0 时疯狂退群的问题

utils/dboperator/engine/sqlite/engine_sqlite.go
=> fix: 修正SQLITE无法正确初始化的问题

dice/platform_adapter_discord.go
=> fix: 修复 Discord Adapter 解析到未知类型 component 时 panic 的问题

dice/ext_dnd5e.go
=> fix: 修复 DND5e `.rc` 指令代投设置变量错误的问题

migrate/v2/enter.go, migrate/v2/v150/v150.go, migrate/v2/v150/v150_attrs.go, migrate/v2/v150/v150_repair.go, model/group_info.go, model/log.go, utils/dboperator/db.go, utils/dboperator/engine/mysql/engine_mysql.go, utils/dboperator/engine/pgsql/engine_pgsql.go, utils/dboperator/engine/sqlite/engine_sqlite.go, utils/upgrader/upgrade.go
如题，通过删掉不能转换为数字或者Data为空的数据来解决问题。目前只见过这一种情况，即数据整体“左移”。
=> feat: 补充V146下GroupInfo错乱的升级修复代码

dice/dice_attrs_manager.go
- 为新创建的属性项添加 LastModifiedTime、LastUsedTime 和 IsSaved 字段
- 修改属性项的释放条件，需同时满足上次修改时间和上次使用时间超过 10 分钟
- 在设置属性项类型时，将 IsSaved 标记为 false，表示未保存状态
注：解决了一开始没有数据的情况下`.st 敏捷50`然后立马`.st show`看不到数据的问题。
很难绷得住，我尝试理了一下逻辑：
当数据库没有数据的时候，代码走初始化的逻辑，初始化的代码没有初始化上次使用时间，所以上次使用时间是空的。
之后`.st show`的时候会调用清理无用数据的代码，检查的时候一看诶这个1970年的老毕登数据，立刻送走落库并清理掉对象。
所以后面的修改全不知道修改到谁身上去了。
之后`.st xxxx`加数值的时候，这次数据库里有值了（虽然是个空的）。
于是触发了上面的逻辑，~~NMD木落你记得上面写时间为什么下面就不写了？！~~，程序就这么水灵灵的跑起来了。
我给释放数据的条件稍作修改，并且把SetSheetType的时候修改未存储标记也打开了，并且把初始化部分补充了点数值。
Close #1289，问题本质为该问题。
=> feat(attributes): 优化属性项的保存和释放逻辑

migrate/v2/v150/v150_attrs.go
=> fix: 修正MySQL的情况下自动更新不会特化建表的BUG

dice/cmd_parse.go, dice/im_session.go, dice/platform_adapter_milky.go
=> fix: 使用 milky 时部分指令代骰失效的问题

dice/builtin_commands.go, dice/dice.go, dice/dice_backup.go, dice/dice_jsvm.go, dice/events/GroupLeaveEvent.go, dice/ext.go, dice/ext_coc7.go, dice/ext_core.go, dice/im_session.go, dice/platform_adapter_gocq.go, dice/platform_adapter_milky.go
=> refactor: 添加 OnGroupLeave 事件，将退群逻辑迁移至扩展中处理

dice/platform_adapter_milky.go
fix: 修复只发送了戳一戳时发不出来的问题
chore: 将海豹消息段转换为 milky 消息端时，戳一戳元素不再发送 warning
=> feat: milky 发送语音

dice/platform_adapter_gocq.go
=> fix: 修复 gocq adapter 戳一戳事件的报错

dice/platform_adapter_gocq.go
=> fix: OneBot private poke

dice/rollvm_migrate.go
=> fix: 修复设置个人骰子面数无法生效的问题

.github/workflows/pr-title-checker.yml, api/utils.go
=> fix(api): 修复网络质量检测中的签名检查，取下发的签名服务器为目标

dice/config.go, dice/dice_jsvm.go, dice/im_session.go
=> fix: 修复插件相关的启用/禁用保存状态问题
